### ISSUE TITLE
`BITFIELD_RO` need optional `encoding offset` by doc https://valkey.io/commands/bitfield_ro/

### ISSUE THREAD

**Issue by ArtemIsmagilov** [valkey-io/valkey-py#114]
I think it's more like a question.
The command does not assume mandatory arguments encoding and offset. Although it is not logical, but valkey can accept bitfield_ro key without parameters. So why don't we add a test with one argument of the key to get an empty array and make the arguments encoding and offset optional in accordance with the documentation?

https://valkey.io/commands/bitfield_ro/

https://github.com/valkey-io/valkey-py/blob/fbf4a31c874262eb021f8129e25c318dfd70e8f3/valkey/commands/core.py#L1601
https://github.com/valkey-io/valkey-py/blob/fbf4a31c874262eb021f8129e25c318dfd70e8f3/tests/test_commands.py#L4834

**Comment by ArtemIsmagilov** [comment]
Semantically more correct
```python
    def bitfield_ro(
        self: Union["Valkey", "AsyncValkey"],
        key: KeyT,
        encoding: Optional[str],
        offset: Optional[BitfieldOffsetT] = None,
        items: Optional[list] = None,
    ) -> ResponseT:
```

**Comment by ArtemIsmagilov** [comment]
test case. This command behavior corresponds to the actual behavior of the server response.
```python
    @skip_if_server_version_lt("6.0.0")
    def test_bitfield_ro(self, r: valkey.Valkey):
        bf = r.bitfield("a")
        resp = bf.set("u8", 8, 255).execute()
        assert resp == [0]

        resp = r.bitfield_ro("a", "u8", 0)
        assert resp == [0]

        items = [("u4", 8), ("u4", 12), ("u4", 13)]
        resp = r.bitfield_ro("a", "u8", 0, items)
        assert resp == [0, 15, 15, 14]
        ### this extra test 
        resp = r.bitfield_ro("a")
        assert resp == []
```

**Comment by aiven-sal** [comment]
Hi!
I'm wondering what would be the point of modifying the command to allow it to be a no-op that returns an hard-coded value?
What would be the use case for something like this in valkey-py?

**Comment by ArtemIsmagilov** [comment]
Hi! 
Don't you think that we are simply skipping an available option that is accepted as valid by the server?
I have no experience in full-fledged client development. Please tell me why this option is wrong for you?

**Comment by aiven-sal** [comment]
> Please tell me why this option is wrong for you?

I don't understand how this can be useful.
It's a no-op and the server returns nothing, even if the key exists. It seems like something that could lead people to make mistakes. Supporting it in valkey-py (which is an high-level client, not just a 1 to 1 mapping to the valkey protocol) doesn't make much sense to me, unless I'm missing something.

**Comment by ArtemIsmagilov** [comment]
Thank you very much for clarifying this issue for me. It looks like you are right. I just compared Python clients for elasticsearch and it has, I hope I am not mistaken, 3 levels of abstraction. 1 - raw commands, 2 - there are methods in full compliance with the documentation (as you said 1 to 1), and 3 - the highest when the methods look like CRUD operations, but under the hood the query is used as close to the meaning as possible.

And it looks like your implementation is the way you see it best for users. And that's great! Thanks again for explaining this solution. It looks like this issue is now closed for me.

**Comment by aiven-sal** [comment]
> I'll tell you honestly, such a trifle, when the original command differs from the client command with the same name, can cause problems. For example, the redis client, written in rust, uses one method 'incr', which contains the logic of both 'incr' and 'incrby'. It would seem to be a great optimization, you can use one method instead of two, but in the end you mixed different functionality and took responsibility for the server logic, although these commands are not just separated.

I have nothing to do with the rust client for Redis and I'm not familiar with their API so I can't really comment on that.

Also I don't want to make a general statement about how closely valkey-py should or should not follow the Valkey protocol. My considerations are specific to this issue.

My point is that if you _know_ that it's a no-op, I wonder why you are doing it. It doesn't make sense to me, unless there is some use case I'm not aware of. If you don't know that, I think that a library like valkey-py can (and should) help you to avoid mistakes.

BTW if you know what you are doing and you _really_ want to do that, you can still use valkey-py to send raw commands:
```
>>> import valkey
>>> valkey.Valkey().execute_command('BITFIELD_RO', 'A')
[]
```

> So, your method really removes this useless case, but this uncertainty leads to future misunderstandings. I still think that you can't take away the server's responsibility, only in the case of very high-level commands, such as for elasticsearch. So it turns out that NoSQL will always be a dark horse with which you need to spend years to start using in production and be sure that everything works exactly as in the documentation, without tricks and additional logic. For example, for most SQL queries, everything is clear, we get what we ask for without optimization, we can ask for an empty array.

I think that the parallel between valkey-py and SQL isn't correct.
Maybe the fact that you see valkey-py as the NoSQL equivalent of SQL is the reason why we have different views on this topic.
valkey-py isn't a query language. It's a library with a specific API built on top of a some DSL.
If you want to make a parallel with the relational world, I think it's closer to an ORM library, like, for example, SQLAlchemy.
When you use the high-level part of such a library, you don't know (or at least you don't need to know) what the actual SQL query looks like.
SQL allows you to write `SELECT 1;` but I don't think that an ORM should have an "AlwaysReturnOne" high-level class to do that, because why would you do that?

**Comment by ArtemIsmagilov** [comment]
Thank you very much for taking me through the details of this solution and also why my approach is not suitable for you. I completely agree with you. The most important point you made is that valkey-py is not a query language, but a DSL. That's the answer to my question.

I'm glad you took the time to answer this question.

**Comment by ArtemIsmagilov** [comment]
Answering your question - why do I need this thing at all?

I will answer - I just want to trust the client who promises me this, to use only what I asked for, so that the methods that implement something correspond to the expected result from the documentation and it does not turn out like this: I ask to send 'A', but it turned out that the request was 'A B C...'. This is the simple responsibility of the server, not the client.

ORM, DSL are great - after all, they solve many problems of a completely different spectrum.
