### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by skewty** [valkey-io/valkey-py#66]
Python 3.9 is just about EOL (no more security updates) and 3.12 isn't yet listed as supported.

Testing for 3.13 should likely get added in at the same time as it is scheduled to release this October.

Reference: [https://devguide.python.org/versions/](https://devguide.python.org/versions/)

**Comment by aiven-sal** [comment]
Hi skewty, thanks for reporting!
Python 3.12 is already supported, why did you get the impression that it isn't?
3.9 is not yet EOL. Maybe you meant 3.8, but we will keep supporting it for a while given that there are still people out there using it (LTS distributions can extend the life of an otherwise unsupported Python version).
Tests for 3.13 will be enabled when it will stop being in `prerelease` status.
