### ISSUE TITLE
async lock not awaitable

### ISSUE THREAD

**Issue by amirreza8002** [valkey-io/valkey-py#90]
hi
`valkey.asyncio.client.lock` is not awaitable and should be called normally
also the Lock class doesn't implement an `__await__`

it might not be a very big deal but i think it hurts consistency of API calls

if you have any takes on this please let me know

**Comment by aiven-sal** [comment]
> hi

Hi!

>  `valkey.asyncio.client.lock` is not awaitable and should be called normally

Yes, I guess that the naming is a bit misleading, because that method isn't _a lock_, but something that returns a lock object. Maybe it should be named differently?

> also the Lock class doesn't implement an `__await__`

I'm not sure what `__await__` should do in this case. Lock already has `__aenter__` and I don't think that it would be a good idea to acquire a lock without a context manager, so we shouldn't make that "easier".

**Comment by amirreza8002** [comment]
hi again👋
it was like a this or that thing

I'm making a client to connect to your async client
and I'm making everything awaitable, thought this might be a code that came with the old codebase and no one remembered to refactor

anyway, i might start to work on cluster client after async, and bother you more, so sorry in advance 🙏
