### ISSUE TITLE
valkey server erroring in github ci

### ISSUE THREAD

**Issue by amirreza8002** [valkey-io/valkey-py#95]
hi
i'm working on [django-valkey](https://github.com/amirreza8002/django-valkey) and in the async branch i'm working on a async herd client.

the tests for this client work without a problem on my machine (i have installed valkey via package manager, not docker).

on [github's actions](https://github.com/amirreza8002/django-valkey/blob/main/.github/workflows/ci.yml) tho, valkey installed via docker. but the settings provided seem to be the same.

```
E           valkey.exceptions.ResponseError: MISCONF Valkey is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Valkey logs for details about the RDB error.
```

this error is returned when github is testing the package.
you can see the tracebacke at [github](https://github.com/amirreza8002/django-valkey/actions/runs/10876610963/job/30176772678#step:8:884)

this only happens with async herd client, even the sync herd client runs without a problem.

if anyone could help me understand this problem i'd be thankful.

**Comment by mkmkme** [comment]
Hey,

For the record, this is the whole error message you're getting:

>MISCONF Valkey is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Valkey logs for details about the RDB error.

It seems that you have either misconfigured Valkey or the CI itself. It would be helpful to fetch the logs from the valkey instance and look for the possible error. 

When you get it, you can start a discussion in [valkey discussions](https://github.com/orgs/valkey-io/discussions) if the logs don't make it clearer.

Since this has nothing to do with valkey-py itself, I'm closing this for now, but feel free to continue the discussion.
